version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: mysql_dev_compose
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD:-password}
      MYSQL_DATABASE: ${DB_DATABASE:-hello_echo_db}
      # MYSQL_USER: ${DB_USER:-user}                # (オプション) root以外のユーザー作成
      # MYSQL_PASSWORD: ${DB_USER_PASSWORD:-user_pass} # (オプション)
    ports:
      - "${DB_PORT:-3306}:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
