-- Create "email_verifications" table
CREATE TABLE `email_verifications` (`id` bigint NOT NULL AUTO_INCREMENT, `created_at` timestamp NOT NULL, `updated_at` timestamp NOT NULL, `email` varchar(255) NOT NULL, `token` varchar(255) NOT NULL, `expired_at` timestamp NOT NULL, PRIMARY KEY (`id`), UNIQUE INDEX `email` (`email`), INDEX `emailverification_email` (`email`), INDEX `emailverification_expired_at` (`expired_at`), INDEX `emailverification_token` (`token`), UNIQUE INDEX `token` (`token`)) CHARSET utf8mb4 COLLATE utf8mb4_bin;
-- Create "companies" table
CREATE TABLE `companies` (`id` bigint NOT NULL AUTO_INCREMENT, `created_at` timestamp NOT NULL, `updated_at` timestamp NOT NULL, `name` varchar(50) NOT NULL, `prefecture` bigint NOT NULL, `city` varchar(255) NOT NULL, `street` varchar(255) NULL, `post_code` varchar(7) NOT NULL, `phone_number` varchar(255) NOT NULL, `url` varchar(255) NULL, PRIMARY KEY (`id`), INDEX `company_name` (`name`)) CHARSET utf8mb4 COLLATE utf8mb4_bin;
-- Create "products" table
CREATE TABLE `products` (`id` bigint NOT NULL AUTO_INCREMENT, `created_at` timestamp NOT NULL, `updated_at` timestamp NOT NULL, `name` varchar(100) NOT NULL, `price` bigint NOT NULL, `description` varchar(500) NULL, PRIMARY KEY (`id`)) CHARSET utf8mb4 COLLATE utf8mb4_bin;
-- Create "lesson_plans" table
CREATE TABLE `lesson_plans` (`id` bigint NOT NULL AUTO_INCREMENT, `created_at` timestamp NOT NULL, `updated_at` timestamp NOT NULL, `title` varchar(500) NOT NULL, `description` varchar(2000) NULL, `location` varchar(500) NULL, `lesson_type` enum('online','offline','online_and_offline') NOT NULL, `annual_max_executions` bigint NOT NULL, `start_month` bigint NOT NULL, `start_day` bigint NOT NULL, `end_month` bigint NOT NULL, `end_day` bigint NOT NULL, `start_time` timestamp NOT NULL, `end_time` timestamp NOT NULL, `company_id` bigint NOT NULL, PRIMARY KEY (`id`), INDEX `lessonplan_company_id` (`company_id`), INDEX `lessonplan_title` (`title`), CONSTRAINT `lesson_plans_companies_lesson_plans` FOREIGN KEY (`company_id`) REFERENCES `companies` (`id`) ON UPDATE NO ACTION ON DELETE NO ACTION) CHARSET utf8mb4 COLLATE utf8mb4_bin;
-- Create "lesson_schedules" table
CREATE TABLE `lesson_schedules` (`id` bigint NOT NULL AUTO_INCREMENT, `created_at` timestamp NOT NULL, `updated_at` timestamp NOT NULL, `title` varchar(100) NOT NULL, `description` varchar(500) NULL, `location` varchar(500) NULL, `lesson_type` enum('online','offline','online_and_offline') NOT NULL, `annual_max_executions` bigint NOT NULL, `start_date` timestamp NOT NULL, `end_date` timestamp NOT NULL, `start_time` timestamp NOT NULL, `end_time` timestamp NOT NULL, `lesson_plan_id` bigint NOT NULL, PRIMARY KEY (`id`), INDEX `lessonschedule_lesson_plan_id` (`lesson_plan_id`), INDEX `lessonschedule_title` (`title`), CONSTRAINT `lesson_schedules_lesson_plans_schedules` FOREIGN KEY (`lesson_plan_id`) REFERENCES `lesson_plans` (`id`) ON UPDATE NO ACTION ON DELETE NO ACTION) CHARSET utf8mb4 COLLATE utf8mb4_bin;
-- Create "education_categories" table
CREATE TABLE `education_categories` (`id` bigint NOT NULL AUTO_INCREMENT, `created_at` timestamp NOT NULL, `updated_at` timestamp NOT NULL, `name` varchar(255) NOT NULL, `code` varchar(255) NOT NULL, `lesson_schedule_education_categories` bigint NULL, PRIMARY KEY (`id`), UNIQUE INDEX `code` (`code`), INDEX `education_categories_lesson_schedules_education_categories` (`lesson_schedule_education_categories`), INDEX `educationcategory_code` (`code`), INDEX `educationcategory_name` (`name`), UNIQUE INDEX `name` (`name`), CONSTRAINT `education_categories_lesson_schedules_education_categories` FOREIGN KEY (`lesson_schedule_education_categories`) REFERENCES `lesson_schedules` (`id`) ON UPDATE NO ACTION ON DELETE SET NULL) CHARSET utf8mb4 COLLATE utf8mb4_bin;
-- Create "grades" table
CREATE TABLE `grades` (`id` bigint NOT NULL AUTO_INCREMENT, `created_at` timestamp NOT NULL, `updated_at` timestamp NOT NULL, `name` varchar(255) NOT NULL, `code` varchar(255) NOT NULL, `lesson_schedule_grades` bigint NULL, PRIMARY KEY (`id`), UNIQUE INDEX `code` (`code`), INDEX `grade_code` (`code`), INDEX `grade_name` (`name`), INDEX `grades_lesson_schedules_grades` (`lesson_schedule_grades`), UNIQUE INDEX `name` (`name`), CONSTRAINT `grades_lesson_schedules_grades` FOREIGN KEY (`lesson_schedule_grades`) REFERENCES `lesson_schedules` (`id`) ON UPDATE NO ACTION ON DELETE SET NULL) CHARSET utf8mb4 COLLATE utf8mb4_bin;
-- Create "schools" table
CREATE TABLE `schools` (`id` bigint NOT NULL AUTO_INCREMENT, `created_at` timestamp NOT NULL, `updated_at` timestamp NOT NULL, `school_type` enum('elementary','juniorHigh','highSchool') NOT NULL, `name` varchar(50) NOT NULL, `email` varchar(200) NULL, `phone_number` varchar(255) NOT NULL, `prefecture` bigint NOT NULL, `city` varchar(255) NOT NULL, `street` varchar(255) NULL, `post_code` varchar(7) NOT NULL, `url` varchar(255) NULL, PRIMARY KEY (`id`), INDEX `school_name` (`name`), INDEX `school_school_type` (`school_type`)) CHARSET utf8mb4 COLLATE utf8mb4_bin;
-- Create "users" table
CREATE TABLE `users` (`id` bigint NOT NULL AUTO_INCREMENT, `created_at` timestamp NOT NULL, `updated_at` timestamp NOT NULL, `user_type` enum('teacher','company_member','admin') NOT NULL DEFAULT "teacher", `first_name` varchar(50) NOT NULL, `family_name` varchar(50) NOT NULL, `email` varchar(100) NOT NULL, `phone_number` varchar(20) NOT NULL, `password` varchar(255) NULL, `company_id` bigint NULL, `school_id` bigint NULL, PRIMARY KEY (`id`), UNIQUE INDEX `email` (`email`), INDEX `user_company_id` (`company_id`), INDEX `user_email` (`email`), INDEX `user_first_name_family_name` (`first_name`, `family_name`), INDEX `user_school_id` (`school_id`), INDEX `user_user_type` (`user_type`), CONSTRAINT `users_companies_members` FOREIGN KEY (`company_id`) REFERENCES `companies` (`id`) ON UPDATE NO ACTION ON DELETE SET NULL, CONSTRAINT `users_schools_teachers` FOREIGN KEY (`school_id`) REFERENCES `schools` (`id`) ON UPDATE NO ACTION ON DELETE SET NULL) CHARSET utf8mb4 COLLATE utf8mb4_bin;
-- Create "inquiries" table
CREATE TABLE `inquiries` (`id` bigint NOT NULL AUTO_INCREMENT, `created_at` timestamp NOT NULL, `updated_at` timestamp NOT NULL, `category` enum('LESSON','RESERVATION','CANCELLATION','OTHER') NOT NULL DEFAULT "OTHER", `inquiry_detail` longtext NOT NULL, `lesson_schedule_id` bigint NOT NULL, `school_id` bigint NOT NULL, `user_id` bigint NOT NULL, PRIMARY KEY (`id`), INDEX `inquiry_category` (`category`), INDEX `inquiry_created_at` (`created_at`), INDEX `inquiry_lesson_schedule_id` (`lesson_schedule_id`), INDEX `inquiry_school_id` (`school_id`), INDEX `inquiry_user_id` (`user_id`), CONSTRAINT `inquiries_lesson_plans_lesson` FOREIGN KEY (`lesson_schedule_id`) REFERENCES `lesson_plans` (`id`) ON UPDATE NO ACTION ON DELETE NO ACTION, CONSTRAINT `inquiries_schools_school` FOREIGN KEY (`school_id`) REFERENCES `schools` (`id`) ON UPDATE NO ACTION ON DELETE NO ACTION, CONSTRAINT `inquiries_users_inquiries` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON UPDATE NO ACTION ON DELETE NO ACTION) CHARSET utf8mb4 COLLATE utf8mb4_bin;
-- Create "lesson_reservations" table
CREATE TABLE `lesson_reservations` (`id` bigint NOT NULL AUTO_INCREMENT, `reservation_status` enum('PENDING','APPROVED','CANCELED') NOT NULL, `count_student` varchar(255) NOT NULL, `graduate` varchar(255) NOT NULL, `subject` varchar(255) NOT NULL, `remarks` varchar(255) NULL, `reservation_confirm_at` timestamp NULL, `lesson_schedule_id` bigint NOT NULL, `school_id` bigint NOT NULL, `user_id` bigint NOT NULL, PRIMARY KEY (`id`), INDEX `lessonreservation_lesson_schedule_id` (`lesson_schedule_id`), INDEX `lessonreservation_reservation_status` (`reservation_status`), INDEX `lessonreservation_school_id` (`school_id`), INDEX `lessonreservation_user_id` (`user_id`), CONSTRAINT `lesson_reservations_lesson_schedules_lesson_reservations` FOREIGN KEY (`lesson_schedule_id`) REFERENCES `lesson_schedules` (`id`) ON UPDATE NO ACTION ON DELETE NO ACTION, CONSTRAINT `lesson_reservations_schools_lesson_reservations` FOREIGN KEY (`school_id`) REFERENCES `schools` (`id`) ON UPDATE NO ACTION ON DELETE NO ACTION, CONSTRAINT `lesson_reservations_users_lesson_reservations` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON UPDATE NO ACTION ON DELETE NO ACTION) CHARSET utf8mb4 COLLATE utf8mb4_bin;
-- Create "lesson_confirmations" table
CREATE TABLE `lesson_confirmations` (`id` bigint NOT NULL AUTO_INCREMENT, `matching_date` timestamp NOT NULL, `start_time` timestamp NOT NULL, `finish_time` timestamp NOT NULL, `remarks` varchar(255) NULL, `lesson_reservation_id` bigint NOT NULL, PRIMARY KEY (`id`), INDEX `lesson_confirmations_lesson_reservations_lesson_confirmation` (`lesson_reservation_id`), CONSTRAINT `lesson_confirmations_lesson_reservations_lesson_confirmation` FOREIGN KEY (`lesson_reservation_id`) REFERENCES `lesson_reservations` (`id`) ON UPDATE NO ACTION ON DELETE NO ACTION) CHARSET utf8mb4 COLLATE utf8mb4_bin;
-- Create "lesson_plan_education_categories" table
CREATE TABLE `lesson_plan_education_categories` (`lesson_plan_id` bigint NOT NULL, `education_category_id` bigint NOT NULL, PRIMARY KEY (`lesson_plan_id`, `education_category_id`), INDEX `lesson_plan_education_categories_education_category_id` (`education_category_id`), CONSTRAINT `lesson_plan_education_categories_education_category_id` FOREIGN KEY (`education_category_id`) REFERENCES `education_categories` (`id`) ON UPDATE NO ACTION ON DELETE CASCADE, CONSTRAINT `lesson_plan_education_categories_lesson_plan_id` FOREIGN KEY (`lesson_plan_id`) REFERENCES `lesson_plans` (`id`) ON UPDATE NO ACTION ON DELETE CASCADE) CHARSET utf8mb4 COLLATE utf8mb4_bin;
-- Create "lesson_plan_grades" table
CREATE TABLE `lesson_plan_grades` (`lesson_plan_id` bigint NOT NULL, `grade_id` bigint NOT NULL, PRIMARY KEY (`lesson_plan_id`, `grade_id`), INDEX `lesson_plan_grades_grade_id` (`grade_id`), CONSTRAINT `lesson_plan_grades_grade_id` FOREIGN KEY (`grade_id`) REFERENCES `grades` (`id`) ON UPDATE NO ACTION ON DELETE CASCADE, CONSTRAINT `lesson_plan_grades_lesson_plan_id` FOREIGN KEY (`lesson_plan_id`) REFERENCES `lesson_plans` (`id`) ON UPDATE NO ACTION ON DELETE CASCADE) CHARSET utf8mb4 COLLATE utf8mb4_bin;
-- Create "subjects" table
CREATE TABLE `subjects` (`id` bigint NOT NULL AUTO_INCREMENT, `created_at` timestamp NOT NULL, `updated_at` timestamp NOT NULL, `name` varchar(255) NOT NULL, `code` varchar(255) NOT NULL, `lesson_schedule_subjects` bigint NULL, PRIMARY KEY (`id`), UNIQUE INDEX `code` (`code`), UNIQUE INDEX `name` (`name`), INDEX `subject_code` (`code`), INDEX `subject_name` (`name`), INDEX `subjects_lesson_schedules_subjects` (`lesson_schedule_subjects`), CONSTRAINT `subjects_lesson_schedules_subjects` FOREIGN KEY (`lesson_schedule_subjects`) REFERENCES `lesson_schedules` (`id`) ON UPDATE NO ACTION ON DELETE SET NULL) CHARSET utf8mb4 COLLATE utf8mb4_bin;
-- Create "lesson_plan_subjects" table
CREATE TABLE `lesson_plan_subjects` (`lesson_plan_id` bigint NOT NULL, `subject_id` bigint NOT NULL, PRIMARY KEY (`lesson_plan_id`, `subject_id`), INDEX `lesson_plan_subjects_subject_id` (`subject_id`), CONSTRAINT `lesson_plan_subjects_lesson_plan_id` FOREIGN KEY (`lesson_plan_id`) REFERENCES `lesson_plans` (`id`) ON UPDATE NO ACTION ON DELETE CASCADE, CONSTRAINT `lesson_plan_subjects_subject_id` FOREIGN KEY (`subject_id`) REFERENCES `subjects` (`id`) ON UPDATE NO ACTION ON DELETE CASCADE) CHARSET utf8mb4 COLLATE utf8mb4_bin;
-- Create "lesson_reservation_preferred_dates" table
CREATE TABLE `lesson_reservation_preferred_dates` (`id` bigint NOT NULL AUTO_INCREMENT, `created_at` timestamp NOT NULL, `updated_at` timestamp NOT NULL, `priority` enum('FIRST','SECOND','THIRD','FOURTH','FIFTH') NOT NULL, `date` timestamp NOT NULL, `start_time` timestamp NOT NULL, `end_time` timestamp NOT NULL, `lesson_reservation_id` bigint NOT NULL, PRIMARY KEY (`id`), INDEX `lessonreservationpreferreddate_date_start_time` (`date`, `start_time`), INDEX `lessonreservationpreferreddate_lesson_reservation_id` (`lesson_reservation_id`), INDEX `lessonreservationpreferreddate_priority` (`priority`), CONSTRAINT `lesson_reservation_preferred_da_8cf36df72ae371fe638a197756d371df` FOREIGN KEY (`lesson_reservation_id`) REFERENCES `lesson_reservations` (`id`) ON UPDATE NO ACTION ON DELETE NO ACTION) CHARSET utf8mb4 COLLATE utf8mb4_bin;
-- Create "upload_files" table
CREATE TABLE `upload_files` (`id` bigint NOT NULL AUTO_INCREMENT, `created_at` timestamp NOT NULL, `updated_at` timestamp NOT NULL, `photo_key` varchar(255) NOT NULL, `user_id` bigint NOT NULL, `lesson_plan_upload_files` bigint NOT NULL, PRIMARY KEY (`id`), INDEX `upload_files_lesson_plans_upload_files` (`lesson_plan_upload_files`), INDEX `uploadfile_photo_key` (`photo_key`), CONSTRAINT `upload_files_lesson_plans_upload_files` FOREIGN KEY (`lesson_plan_upload_files`) REFERENCES `lesson_plans` (`id`) ON UPDATE NO ACTION ON DELETE NO ACTION) CHARSET utf8mb4 COLLATE utf8mb4_bin;
