-- Create "education_categories" table
CREATE TABLE `education_categories` (`id` bigint NOT NULL AUTO_INCREMENT, `name` varchar(255) NOT NULL, `code` varchar(255) NOT NULL, PRIMARY KEY (`id`), UNIQUE INDEX `code` (`code`), INDEX `educationcategory_code` (`code`), INDEX `educationcategory_name` (`name`), UNIQUE INDEX `name` (`name`)) CHARSET utf8mb4 COLLATE utf8mb4_bin;
-- Create "companies" table
CREATE TABLE `companies` (`id` bigint NOT NULL AUTO_INCREMENT, `name` varchar(50) NOT NULL, `prefecture` bigint NOT NULL, `city` varchar(255) NOT NULL, `street` varchar(255) NULL, `post_code` varchar(7) NOT NULL, `phone_number` varchar(255) NOT NULL, `url` varchar(255) NULL, `created_at` timestamp NOT NULL, `updated_at` timestamp NOT NULL, PRIMARY KEY (`id`), INDEX `company_name` (`name`)) CHARSET utf8mb4 COLLATE utf8mb4_bin;
-- Create "lesson_plans" table
CREATE TABLE `lesson_plans` (`id` bigint NOT NULL AUTO_INCREMENT, `title` varchar(500) NOT NULL, `description` varchar(2000) NULL, `location` varchar(500) NULL, `lesson_type` enum('online','offline','online_and_offline') NOT NULL, `annual_max_executions` bigint NOT NULL, `start_month` bigint NOT NULL, `start_day` bigint NOT NULL, `end_month` bigint NOT NULL, `end_day` bigint NOT NULL, `start_time` timestamp NOT NULL, `end_time` timestamp NOT NULL, `updated_at` timestamp NOT NULL, `created_at` timestamp NOT NULL, `company_id` bigint NOT NULL, PRIMARY KEY (`id`), INDEX `lessonplan_company_id` (`company_id`), INDEX `lessonplan_title` (`title`), CONSTRAINT `lesson_plans_companies_lesson_plans` FOREIGN KEY (`company_id`) REFERENCES `companies` (`id`) ON UPDATE NO ACTION ON DELETE NO ACTION) CHARSET utf8mb4 COLLATE utf8mb4_bin;
-- Create "lesson_plan_education_categories" table
CREATE TABLE `lesson_plan_education_categories` (`lesson_plan_id` bigint NOT NULL, `education_category_id` bigint NOT NULL, PRIMARY KEY (`lesson_plan_id`, `education_category_id`), INDEX `lesson_plan_education_categories_education_category_id` (`education_category_id`), CONSTRAINT `lesson_plan_education_categories_education_category_id` FOREIGN KEY (`education_category_id`) REFERENCES `education_categories` (`id`) ON UPDATE NO ACTION ON DELETE CASCADE, CONSTRAINT `lesson_plan_education_categories_lesson_plan_id` FOREIGN KEY (`lesson_plan_id`) REFERENCES `lesson_plans` (`id`) ON UPDATE NO ACTION ON DELETE CASCADE) CHARSET utf8mb4 COLLATE utf8mb4_bin;
-- Create "grades" table
CREATE TABLE `grades` (`id` bigint NOT NULL AUTO_INCREMENT, `name` varchar(255) NOT NULL, `code` varchar(255) NOT NULL, PRIMARY KEY (`id`), UNIQUE INDEX `code` (`code`), INDEX `grade_code` (`code`), INDEX `grade_name` (`name`), UNIQUE INDEX `name` (`name`)) CHARSET utf8mb4 COLLATE utf8mb4_bin;
-- Create "lesson_plan_grades" table
CREATE TABLE `lesson_plan_grades` (`lesson_plan_id` bigint NOT NULL, `grade_id` bigint NOT NULL, PRIMARY KEY (`lesson_plan_id`, `grade_id`), INDEX `lesson_plan_grades_grade_id` (`grade_id`), CONSTRAINT `lesson_plan_grades_grade_id` FOREIGN KEY (`grade_id`) REFERENCES `grades` (`id`) ON UPDATE NO ACTION ON DELETE CASCADE, CONSTRAINT `lesson_plan_grades_lesson_plan_id` FOREIGN KEY (`lesson_plan_id`) REFERENCES `lesson_plans` (`id`) ON UPDATE NO ACTION ON DELETE CASCADE) CHARSET utf8mb4 COLLATE utf8mb4_bin;
-- Create "subjects" table
CREATE TABLE `subjects` (`id` bigint NOT NULL AUTO_INCREMENT, `name` varchar(255) NOT NULL, `code` varchar(255) NOT NULL, PRIMARY KEY (`id`), UNIQUE INDEX `code` (`code`), UNIQUE INDEX `name` (`name`), INDEX `subject_code` (`code`), INDEX `subject_name` (`name`)) CHARSET utf8mb4 COLLATE utf8mb4_bin;
-- Create "lesson_plan_subjects" table
CREATE TABLE `lesson_plan_subjects` (`lesson_plan_id` bigint NOT NULL, `subject_id` bigint NOT NULL, PRIMARY KEY (`lesson_plan_id`, `subject_id`), INDEX `lesson_plan_subjects_subject_id` (`subject_id`), CONSTRAINT `lesson_plan_subjects_lesson_plan_id` FOREIGN KEY (`lesson_plan_id`) REFERENCES `lesson_plans` (`id`) ON UPDATE NO ACTION ON DELETE CASCADE, CONSTRAINT `lesson_plan_subjects_subject_id` FOREIGN KEY (`subject_id`) REFERENCES `subjects` (`id`) ON UPDATE NO ACTION ON DELETE CASCADE) CHARSET utf8mb4 COLLATE utf8mb4_bin;
-- Create "lesson_schedules" table
CREATE TABLE `lesson_schedules` (`id` bigint NOT NULL AUTO_INCREMENT, `title` varchar(100) NOT NULL, `description` varchar(500) NULL, `location` varchar(500) NULL, `lesson_type` enum('online','offline','online_and_offline') NOT NULL, `annual_max_executions` bigint NOT NULL, `start_date` timestamp NOT NULL, `end_date` timestamp NOT NULL, `start_time` timestamp NOT NULL, `end_time` timestamp NOT NULL, `updated_at` timestamp NOT NULL, `created_at` timestamp NOT NULL, `lesson_plan_id` bigint NOT NULL, PRIMARY KEY (`id`), INDEX `lessonschedule_lesson_plan_id` (`lesson_plan_id`), INDEX `lessonschedule_title` (`title`), CONSTRAINT `lesson_schedules_lesson_plans_schedules` FOREIGN KEY (`lesson_plan_id`) REFERENCES `lesson_plans` (`id`) ON UPDATE NO ACTION ON DELETE NO ACTION) CHARSET utf8mb4 COLLATE utf8mb4_bin;
-- Create "schools" table
CREATE TABLE `schools` (`id` bigint NOT NULL AUTO_INCREMENT, `school_type` enum('elementary','juniorHigh','highSchool') NOT NULL, `name` varchar(50) NOT NULL, `email` varchar(200) NULL, `phone_number` varchar(255) NOT NULL, `prefecture` bigint NOT NULL, `city` varchar(255) NOT NULL, `street` varchar(255) NULL, `post_code` varchar(7) NOT NULL, `url` varchar(255) NULL, `created_at` timestamp NOT NULL, `updated_at` timestamp NOT NULL, PRIMARY KEY (`id`), INDEX `school_name` (`name`), INDEX `school_school_type` (`school_type`)) CHARSET utf8mb4 COLLATE utf8mb4_bin;
-- Modify "users" table
ALTER TABLE `users` MODIFY COLUMN `first_name` varchar(50) NOT NULL, MODIFY COLUMN `family_name` varchar(50) NOT NULL, MODIFY COLUMN `password` varchar(255) NULL, ADD COLUMN `user_type` enum('teacher','company_member','admin') NOT NULL DEFAULT "teacher", ADD COLUMN `phone_number` varchar(20) NOT NULL, ADD COLUMN `company_id` bigint NULL, ADD COLUMN `school_id` bigint NULL, ADD INDEX `user_company_id` (`company_id`), ADD INDEX `user_email` (`email`), ADD INDEX `user_school_id` (`school_id`), ADD INDEX `user_user_type` (`user_type`), ADD CONSTRAINT `users_companies_members` FOREIGN KEY (`company_id`) REFERENCES `companies` (`id`) ON UPDATE NO ACTION ON DELETE SET NULL, ADD CONSTRAINT `users_schools_teachers` FOREIGN KEY (`school_id`) REFERENCES `schools` (`id`) ON UPDATE NO ACTION ON DELETE SET NULL;
