-- Modify "lesson_plan_education_categories" table
ALTER TABLE `lesson_plan_education_categories` ADD COLUMN `id` bigint NOT NULL AUTO_INCREMENT, ADD COLUMN `created_at` timestamp NOT NULL, ADD COLUMN `updated_at` timestamp NOT NULL, DROP PRIMARY KEY, ADD PRIMARY KEY (`id`), DROP INDEX `lesson_plan_education_categories_education_category_id`, ADD INDEX `lessonplaneducationcategory_education_category_id` (`education_category_id`), ADD INDEX `lessonplaneducationcategory_lesson_plan_id` (`lesson_plan_id`), ADD UNIQUE INDEX `lessonplaneducationcategory_lesson_plan_id_education_category_id` (`lesson_plan_id`, `education_category_id`), DROP FOREIGN KEY `lesson_plan_education_categories_education_category_id`, DROP FOREIGN KEY `lesson_plan_education_categories_lesson_plan_id`, ADD CONSTRAINT `lesson_plan_education_categorie_4b44d5cbc5918daaeb4bb9f228f0beaf` FOREIGN KEY (`education_category_id`) REFERENCES `education_categories` (`id`) ON UPDATE NO ACTION ON DELETE NO ACTION, ADD CONSTRAINT `lesson_plan_education_categories_lesson_plans_lesson_plan` FOREIGN KEY (`lesson_plan_id`) REFERENCES `lesson_plans` (`id`) ON UPDATE NO ACTION ON DELETE NO ACTION;
-- Modify "grades" table
ALTER TABLE `grades` DROP COLUMN `name`, ADD INDEX `grade_code_number` (`code_number`);
-- Modify "lesson_plan_grades" table
ALTER TABLE `lesson_plan_grades` ADD COLUMN `id` bigint NOT NULL AUTO_INCREMENT, ADD COLUMN `created_at` timestamp NOT NULL, ADD COLUMN `updated_at` timestamp NOT NULL, DROP PRIMARY KEY, ADD PRIMARY KEY (`id`), DROP INDEX `lesson_plan_grades_grade_id`, ADD INDEX `lessonplangrade_grade_id` (`grade_id`), ADD INDEX `lessonplangrade_lesson_plan_id` (`lesson_plan_id`), ADD UNIQUE INDEX `lessonplangrade_lesson_plan_id_grade_id` (`lesson_plan_id`, `grade_id`), DROP FOREIGN KEY `lesson_plan_grades_grade_id`, DROP FOREIGN KEY `lesson_plan_grades_lesson_plan_id`, ADD CONSTRAINT `lesson_plan_grades_grades_grade` FOREIGN KEY (`grade_id`) REFERENCES `grades` (`id`) ON UPDATE NO ACTION ON DELETE NO ACTION, ADD CONSTRAINT `lesson_plan_grades_lesson_plans_lesson_plan` FOREIGN KEY (`lesson_plan_id`) REFERENCES `lesson_plans` (`id`) ON UPDATE NO ACTION ON DELETE NO ACTION;
-- Modify "lesson_plan_subjects" table
ALTER TABLE `lesson_plan_subjects` ADD COLUMN `id` bigint NOT NULL AUTO_INCREMENT, ADD COLUMN `created_at` timestamp NOT NULL, ADD COLUMN `updated_at` timestamp NOT NULL, DROP PRIMARY KEY, ADD PRIMARY KEY (`id`), DROP INDEX `lesson_plan_subjects_subject_id`, ADD INDEX `lessonplansubject_lesson_plan_id` (`lesson_plan_id`), ADD UNIQUE INDEX `lessonplansubject_lesson_plan_id_subject_id` (`lesson_plan_id`, `subject_id`), ADD INDEX `lessonplansubject_subject_id` (`subject_id`), DROP FOREIGN KEY `lesson_plan_subjects_lesson_plan_id`, DROP FOREIGN KEY `lesson_plan_subjects_subject_id`, ADD CONSTRAINT `lesson_plan_subjects_lesson_plans_lesson_plan` FOREIGN KEY (`lesson_plan_id`) REFERENCES `lesson_plans` (`id`) ON UPDATE NO ACTION ON DELETE NO ACTION, ADD CONSTRAINT `lesson_plan_subjects_subjects_subject` FOREIGN KEY (`subject_id`) REFERENCES `subjects` (`id`) ON UPDATE NO ACTION ON DELETE NO ACTION;
-- Modify "upload_files" table
ALTER TABLE `upload_files` DROP COLUMN `lesson_plan_upload_files`, DROP FOREIGN KEY `upload_files_lesson_plans_upload_files`;
-- Create "lesson_plan_upload_files" table
CREATE TABLE `lesson_plan_upload_files` (`id` bigint NOT NULL AUTO_INCREMENT, `created_at` timestamp NOT NULL, `updated_at` timestamp NOT NULL, `lesson_plan_id` bigint NOT NULL, `upload_file_id` bigint NOT NULL, PRIMARY KEY (`id`), INDEX `lessonplanuploadfile_lesson_plan_id` (`lesson_plan_id`), UNIQUE INDEX `lessonplanuploadfile_lesson_plan_id_upload_file_id` (`lesson_plan_id`, `upload_file_id`), INDEX `lessonplanuploadfile_upload_file_id` (`upload_file_id`), CONSTRAINT `lesson_plan_upload_files_lesson_plans_lesson_plan` FOREIGN KEY (`lesson_plan_id`) REFERENCES `lesson_plans` (`id`) ON UPDATE NO ACTION ON DELETE NO ACTION, CONSTRAINT `lesson_plan_upload_files_upload_files_upload_file` FOREIGN KEY (`upload_file_id`) REFERENCES `upload_files` (`id`) ON UPDATE NO ACTION ON DELETE NO ACTION) CHARSET utf8mb4 COLLATE utf8mb4_bin;
