// Code generated by ent, DO NOT EDIT.

package lessonplan

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/takuyakawta/spot-teacher-sample/db/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.LessonPlan {
	return predicate.LessonPlan(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.LessonPlan {
	return predicate.LessonPlan(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.LessonPlan {
	return predicate.LessonPlan(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.LessonPlan {
	return predicate.LessonPlan(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.LessonPlan {
	return predicate.LessonPlan(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.LessonPlan {
	return predicate.LessonPlan(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.LessonPlan {
	return predicate.LessonPlan(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.LessonPlan {
	return predicate.LessonPlan(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.LessonPlan {
	return predicate.LessonPlan(sql.FieldLTE(FieldID, id))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.LessonPlan {
	return predicate.LessonPlan(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.LessonPlan {
	return predicate.LessonPlan(sql.FieldEQ(FieldUpdatedAt, v))
}

// CompanyID applies equality check predicate on the "company_id" field. It's identical to CompanyIDEQ.
func CompanyID(v int) predicate.LessonPlan {
	return predicate.LessonPlan(sql.FieldEQ(FieldCompanyID, v))
}

// Title applies equality check predicate on the "title" field. It's identical to TitleEQ.
func Title(v string) predicate.LessonPlan {
	return predicate.LessonPlan(sql.FieldEQ(FieldTitle, v))
}

// Description applies equality check predicate on the "description" field. It's identical to DescriptionEQ.
func Description(v string) predicate.LessonPlan {
	return predicate.LessonPlan(sql.FieldEQ(FieldDescription, v))
}

// Location applies equality check predicate on the "location" field. It's identical to LocationEQ.
func Location(v string) predicate.LessonPlan {
	return predicate.LessonPlan(sql.FieldEQ(FieldLocation, v))
}

// AnnualMaxExecutions applies equality check predicate on the "annual_max_executions" field. It's identical to AnnualMaxExecutionsEQ.
func AnnualMaxExecutions(v int) predicate.LessonPlan {
	return predicate.LessonPlan(sql.FieldEQ(FieldAnnualMaxExecutions, v))
}

// StartMonth applies equality check predicate on the "start_month" field. It's identical to StartMonthEQ.
func StartMonth(v int) predicate.LessonPlan {
	return predicate.LessonPlan(sql.FieldEQ(FieldStartMonth, v))
}

// StartDay applies equality check predicate on the "start_day" field. It's identical to StartDayEQ.
func StartDay(v int) predicate.LessonPlan {
	return predicate.LessonPlan(sql.FieldEQ(FieldStartDay, v))
}

// EndMonth applies equality check predicate on the "end_month" field. It's identical to EndMonthEQ.
func EndMonth(v int) predicate.LessonPlan {
	return predicate.LessonPlan(sql.FieldEQ(FieldEndMonth, v))
}

// EndDay applies equality check predicate on the "end_day" field. It's identical to EndDayEQ.
func EndDay(v int) predicate.LessonPlan {
	return predicate.LessonPlan(sql.FieldEQ(FieldEndDay, v))
}

// StartTime applies equality check predicate on the "start_time" field. It's identical to StartTimeEQ.
func StartTime(v time.Time) predicate.LessonPlan {
	return predicate.LessonPlan(sql.FieldEQ(FieldStartTime, v))
}

// EndTime applies equality check predicate on the "end_time" field. It's identical to EndTimeEQ.
func EndTime(v time.Time) predicate.LessonPlan {
	return predicate.LessonPlan(sql.FieldEQ(FieldEndTime, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.LessonPlan {
	return predicate.LessonPlan(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.LessonPlan {
	return predicate.LessonPlan(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.LessonPlan {
	return predicate.LessonPlan(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.LessonPlan {
	return predicate.LessonPlan(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.LessonPlan {
	return predicate.LessonPlan(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.LessonPlan {
	return predicate.LessonPlan(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.LessonPlan {
	return predicate.LessonPlan(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.LessonPlan {
	return predicate.LessonPlan(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.LessonPlan {
	return predicate.LessonPlan(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.LessonPlan {
	return predicate.LessonPlan(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.LessonPlan {
	return predicate.LessonPlan(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.LessonPlan {
	return predicate.LessonPlan(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.LessonPlan {
	return predicate.LessonPlan(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.LessonPlan {
	return predicate.LessonPlan(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.LessonPlan {
	return predicate.LessonPlan(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.LessonPlan {
	return predicate.LessonPlan(sql.FieldLTE(FieldUpdatedAt, v))
}

// CompanyIDEQ applies the EQ predicate on the "company_id" field.
func CompanyIDEQ(v int) predicate.LessonPlan {
	return predicate.LessonPlan(sql.FieldEQ(FieldCompanyID, v))
}

// CompanyIDNEQ applies the NEQ predicate on the "company_id" field.
func CompanyIDNEQ(v int) predicate.LessonPlan {
	return predicate.LessonPlan(sql.FieldNEQ(FieldCompanyID, v))
}

// CompanyIDIn applies the In predicate on the "company_id" field.
func CompanyIDIn(vs ...int) predicate.LessonPlan {
	return predicate.LessonPlan(sql.FieldIn(FieldCompanyID, vs...))
}

// CompanyIDNotIn applies the NotIn predicate on the "company_id" field.
func CompanyIDNotIn(vs ...int) predicate.LessonPlan {
	return predicate.LessonPlan(sql.FieldNotIn(FieldCompanyID, vs...))
}

// TitleEQ applies the EQ predicate on the "title" field.
func TitleEQ(v string) predicate.LessonPlan {
	return predicate.LessonPlan(sql.FieldEQ(FieldTitle, v))
}

// TitleNEQ applies the NEQ predicate on the "title" field.
func TitleNEQ(v string) predicate.LessonPlan {
	return predicate.LessonPlan(sql.FieldNEQ(FieldTitle, v))
}

// TitleIn applies the In predicate on the "title" field.
func TitleIn(vs ...string) predicate.LessonPlan {
	return predicate.LessonPlan(sql.FieldIn(FieldTitle, vs...))
}

// TitleNotIn applies the NotIn predicate on the "title" field.
func TitleNotIn(vs ...string) predicate.LessonPlan {
	return predicate.LessonPlan(sql.FieldNotIn(FieldTitle, vs...))
}

// TitleGT applies the GT predicate on the "title" field.
func TitleGT(v string) predicate.LessonPlan {
	return predicate.LessonPlan(sql.FieldGT(FieldTitle, v))
}

// TitleGTE applies the GTE predicate on the "title" field.
func TitleGTE(v string) predicate.LessonPlan {
	return predicate.LessonPlan(sql.FieldGTE(FieldTitle, v))
}

// TitleLT applies the LT predicate on the "title" field.
func TitleLT(v string) predicate.LessonPlan {
	return predicate.LessonPlan(sql.FieldLT(FieldTitle, v))
}

// TitleLTE applies the LTE predicate on the "title" field.
func TitleLTE(v string) predicate.LessonPlan {
	return predicate.LessonPlan(sql.FieldLTE(FieldTitle, v))
}

// TitleContains applies the Contains predicate on the "title" field.
func TitleContains(v string) predicate.LessonPlan {
	return predicate.LessonPlan(sql.FieldContains(FieldTitle, v))
}

// TitleHasPrefix applies the HasPrefix predicate on the "title" field.
func TitleHasPrefix(v string) predicate.LessonPlan {
	return predicate.LessonPlan(sql.FieldHasPrefix(FieldTitle, v))
}

// TitleHasSuffix applies the HasSuffix predicate on the "title" field.
func TitleHasSuffix(v string) predicate.LessonPlan {
	return predicate.LessonPlan(sql.FieldHasSuffix(FieldTitle, v))
}

// TitleEqualFold applies the EqualFold predicate on the "title" field.
func TitleEqualFold(v string) predicate.LessonPlan {
	return predicate.LessonPlan(sql.FieldEqualFold(FieldTitle, v))
}

// TitleContainsFold applies the ContainsFold predicate on the "title" field.
func TitleContainsFold(v string) predicate.LessonPlan {
	return predicate.LessonPlan(sql.FieldContainsFold(FieldTitle, v))
}

// DescriptionEQ applies the EQ predicate on the "description" field.
func DescriptionEQ(v string) predicate.LessonPlan {
	return predicate.LessonPlan(sql.FieldEQ(FieldDescription, v))
}

// DescriptionNEQ applies the NEQ predicate on the "description" field.
func DescriptionNEQ(v string) predicate.LessonPlan {
	return predicate.LessonPlan(sql.FieldNEQ(FieldDescription, v))
}

// DescriptionIn applies the In predicate on the "description" field.
func DescriptionIn(vs ...string) predicate.LessonPlan {
	return predicate.LessonPlan(sql.FieldIn(FieldDescription, vs...))
}

// DescriptionNotIn applies the NotIn predicate on the "description" field.
func DescriptionNotIn(vs ...string) predicate.LessonPlan {
	return predicate.LessonPlan(sql.FieldNotIn(FieldDescription, vs...))
}

// DescriptionGT applies the GT predicate on the "description" field.
func DescriptionGT(v string) predicate.LessonPlan {
	return predicate.LessonPlan(sql.FieldGT(FieldDescription, v))
}

// DescriptionGTE applies the GTE predicate on the "description" field.
func DescriptionGTE(v string) predicate.LessonPlan {
	return predicate.LessonPlan(sql.FieldGTE(FieldDescription, v))
}

// DescriptionLT applies the LT predicate on the "description" field.
func DescriptionLT(v string) predicate.LessonPlan {
	return predicate.LessonPlan(sql.FieldLT(FieldDescription, v))
}

// DescriptionLTE applies the LTE predicate on the "description" field.
func DescriptionLTE(v string) predicate.LessonPlan {
	return predicate.LessonPlan(sql.FieldLTE(FieldDescription, v))
}

// DescriptionContains applies the Contains predicate on the "description" field.
func DescriptionContains(v string) predicate.LessonPlan {
	return predicate.LessonPlan(sql.FieldContains(FieldDescription, v))
}

// DescriptionHasPrefix applies the HasPrefix predicate on the "description" field.
func DescriptionHasPrefix(v string) predicate.LessonPlan {
	return predicate.LessonPlan(sql.FieldHasPrefix(FieldDescription, v))
}

// DescriptionHasSuffix applies the HasSuffix predicate on the "description" field.
func DescriptionHasSuffix(v string) predicate.LessonPlan {
	return predicate.LessonPlan(sql.FieldHasSuffix(FieldDescription, v))
}

// DescriptionIsNil applies the IsNil predicate on the "description" field.
func DescriptionIsNil() predicate.LessonPlan {
	return predicate.LessonPlan(sql.FieldIsNull(FieldDescription))
}

// DescriptionNotNil applies the NotNil predicate on the "description" field.
func DescriptionNotNil() predicate.LessonPlan {
	return predicate.LessonPlan(sql.FieldNotNull(FieldDescription))
}

// DescriptionEqualFold applies the EqualFold predicate on the "description" field.
func DescriptionEqualFold(v string) predicate.LessonPlan {
	return predicate.LessonPlan(sql.FieldEqualFold(FieldDescription, v))
}

// DescriptionContainsFold applies the ContainsFold predicate on the "description" field.
func DescriptionContainsFold(v string) predicate.LessonPlan {
	return predicate.LessonPlan(sql.FieldContainsFold(FieldDescription, v))
}

// LocationEQ applies the EQ predicate on the "location" field.
func LocationEQ(v string) predicate.LessonPlan {
	return predicate.LessonPlan(sql.FieldEQ(FieldLocation, v))
}

// LocationNEQ applies the NEQ predicate on the "location" field.
func LocationNEQ(v string) predicate.LessonPlan {
	return predicate.LessonPlan(sql.FieldNEQ(FieldLocation, v))
}

// LocationIn applies the In predicate on the "location" field.
func LocationIn(vs ...string) predicate.LessonPlan {
	return predicate.LessonPlan(sql.FieldIn(FieldLocation, vs...))
}

// LocationNotIn applies the NotIn predicate on the "location" field.
func LocationNotIn(vs ...string) predicate.LessonPlan {
	return predicate.LessonPlan(sql.FieldNotIn(FieldLocation, vs...))
}

// LocationGT applies the GT predicate on the "location" field.
func LocationGT(v string) predicate.LessonPlan {
	return predicate.LessonPlan(sql.FieldGT(FieldLocation, v))
}

// LocationGTE applies the GTE predicate on the "location" field.
func LocationGTE(v string) predicate.LessonPlan {
	return predicate.LessonPlan(sql.FieldGTE(FieldLocation, v))
}

// LocationLT applies the LT predicate on the "location" field.
func LocationLT(v string) predicate.LessonPlan {
	return predicate.LessonPlan(sql.FieldLT(FieldLocation, v))
}

// LocationLTE applies the LTE predicate on the "location" field.
func LocationLTE(v string) predicate.LessonPlan {
	return predicate.LessonPlan(sql.FieldLTE(FieldLocation, v))
}

// LocationContains applies the Contains predicate on the "location" field.
func LocationContains(v string) predicate.LessonPlan {
	return predicate.LessonPlan(sql.FieldContains(FieldLocation, v))
}

// LocationHasPrefix applies the HasPrefix predicate on the "location" field.
func LocationHasPrefix(v string) predicate.LessonPlan {
	return predicate.LessonPlan(sql.FieldHasPrefix(FieldLocation, v))
}

// LocationHasSuffix applies the HasSuffix predicate on the "location" field.
func LocationHasSuffix(v string) predicate.LessonPlan {
	return predicate.LessonPlan(sql.FieldHasSuffix(FieldLocation, v))
}

// LocationIsNil applies the IsNil predicate on the "location" field.
func LocationIsNil() predicate.LessonPlan {
	return predicate.LessonPlan(sql.FieldIsNull(FieldLocation))
}

// LocationNotNil applies the NotNil predicate on the "location" field.
func LocationNotNil() predicate.LessonPlan {
	return predicate.LessonPlan(sql.FieldNotNull(FieldLocation))
}

// LocationEqualFold applies the EqualFold predicate on the "location" field.
func LocationEqualFold(v string) predicate.LessonPlan {
	return predicate.LessonPlan(sql.FieldEqualFold(FieldLocation, v))
}

// LocationContainsFold applies the ContainsFold predicate on the "location" field.
func LocationContainsFold(v string) predicate.LessonPlan {
	return predicate.LessonPlan(sql.FieldContainsFold(FieldLocation, v))
}

// LessonTypeEQ applies the EQ predicate on the "lesson_type" field.
func LessonTypeEQ(v LessonType) predicate.LessonPlan {
	return predicate.LessonPlan(sql.FieldEQ(FieldLessonType, v))
}

// LessonTypeNEQ applies the NEQ predicate on the "lesson_type" field.
func LessonTypeNEQ(v LessonType) predicate.LessonPlan {
	return predicate.LessonPlan(sql.FieldNEQ(FieldLessonType, v))
}

// LessonTypeIn applies the In predicate on the "lesson_type" field.
func LessonTypeIn(vs ...LessonType) predicate.LessonPlan {
	return predicate.LessonPlan(sql.FieldIn(FieldLessonType, vs...))
}

// LessonTypeNotIn applies the NotIn predicate on the "lesson_type" field.
func LessonTypeNotIn(vs ...LessonType) predicate.LessonPlan {
	return predicate.LessonPlan(sql.FieldNotIn(FieldLessonType, vs...))
}

// AnnualMaxExecutionsEQ applies the EQ predicate on the "annual_max_executions" field.
func AnnualMaxExecutionsEQ(v int) predicate.LessonPlan {
	return predicate.LessonPlan(sql.FieldEQ(FieldAnnualMaxExecutions, v))
}

// AnnualMaxExecutionsNEQ applies the NEQ predicate on the "annual_max_executions" field.
func AnnualMaxExecutionsNEQ(v int) predicate.LessonPlan {
	return predicate.LessonPlan(sql.FieldNEQ(FieldAnnualMaxExecutions, v))
}

// AnnualMaxExecutionsIn applies the In predicate on the "annual_max_executions" field.
func AnnualMaxExecutionsIn(vs ...int) predicate.LessonPlan {
	return predicate.LessonPlan(sql.FieldIn(FieldAnnualMaxExecutions, vs...))
}

// AnnualMaxExecutionsNotIn applies the NotIn predicate on the "annual_max_executions" field.
func AnnualMaxExecutionsNotIn(vs ...int) predicate.LessonPlan {
	return predicate.LessonPlan(sql.FieldNotIn(FieldAnnualMaxExecutions, vs...))
}

// AnnualMaxExecutionsGT applies the GT predicate on the "annual_max_executions" field.
func AnnualMaxExecutionsGT(v int) predicate.LessonPlan {
	return predicate.LessonPlan(sql.FieldGT(FieldAnnualMaxExecutions, v))
}

// AnnualMaxExecutionsGTE applies the GTE predicate on the "annual_max_executions" field.
func AnnualMaxExecutionsGTE(v int) predicate.LessonPlan {
	return predicate.LessonPlan(sql.FieldGTE(FieldAnnualMaxExecutions, v))
}

// AnnualMaxExecutionsLT applies the LT predicate on the "annual_max_executions" field.
func AnnualMaxExecutionsLT(v int) predicate.LessonPlan {
	return predicate.LessonPlan(sql.FieldLT(FieldAnnualMaxExecutions, v))
}

// AnnualMaxExecutionsLTE applies the LTE predicate on the "annual_max_executions" field.
func AnnualMaxExecutionsLTE(v int) predicate.LessonPlan {
	return predicate.LessonPlan(sql.FieldLTE(FieldAnnualMaxExecutions, v))
}

// StartMonthEQ applies the EQ predicate on the "start_month" field.
func StartMonthEQ(v int) predicate.LessonPlan {
	return predicate.LessonPlan(sql.FieldEQ(FieldStartMonth, v))
}

// StartMonthNEQ applies the NEQ predicate on the "start_month" field.
func StartMonthNEQ(v int) predicate.LessonPlan {
	return predicate.LessonPlan(sql.FieldNEQ(FieldStartMonth, v))
}

// StartMonthIn applies the In predicate on the "start_month" field.
func StartMonthIn(vs ...int) predicate.LessonPlan {
	return predicate.LessonPlan(sql.FieldIn(FieldStartMonth, vs...))
}

// StartMonthNotIn applies the NotIn predicate on the "start_month" field.
func StartMonthNotIn(vs ...int) predicate.LessonPlan {
	return predicate.LessonPlan(sql.FieldNotIn(FieldStartMonth, vs...))
}

// StartMonthGT applies the GT predicate on the "start_month" field.
func StartMonthGT(v int) predicate.LessonPlan {
	return predicate.LessonPlan(sql.FieldGT(FieldStartMonth, v))
}

// StartMonthGTE applies the GTE predicate on the "start_month" field.
func StartMonthGTE(v int) predicate.LessonPlan {
	return predicate.LessonPlan(sql.FieldGTE(FieldStartMonth, v))
}

// StartMonthLT applies the LT predicate on the "start_month" field.
func StartMonthLT(v int) predicate.LessonPlan {
	return predicate.LessonPlan(sql.FieldLT(FieldStartMonth, v))
}

// StartMonthLTE applies the LTE predicate on the "start_month" field.
func StartMonthLTE(v int) predicate.LessonPlan {
	return predicate.LessonPlan(sql.FieldLTE(FieldStartMonth, v))
}

// StartDayEQ applies the EQ predicate on the "start_day" field.
func StartDayEQ(v int) predicate.LessonPlan {
	return predicate.LessonPlan(sql.FieldEQ(FieldStartDay, v))
}

// StartDayNEQ applies the NEQ predicate on the "start_day" field.
func StartDayNEQ(v int) predicate.LessonPlan {
	return predicate.LessonPlan(sql.FieldNEQ(FieldStartDay, v))
}

// StartDayIn applies the In predicate on the "start_day" field.
func StartDayIn(vs ...int) predicate.LessonPlan {
	return predicate.LessonPlan(sql.FieldIn(FieldStartDay, vs...))
}

// StartDayNotIn applies the NotIn predicate on the "start_day" field.
func StartDayNotIn(vs ...int) predicate.LessonPlan {
	return predicate.LessonPlan(sql.FieldNotIn(FieldStartDay, vs...))
}

// StartDayGT applies the GT predicate on the "start_day" field.
func StartDayGT(v int) predicate.LessonPlan {
	return predicate.LessonPlan(sql.FieldGT(FieldStartDay, v))
}

// StartDayGTE applies the GTE predicate on the "start_day" field.
func StartDayGTE(v int) predicate.LessonPlan {
	return predicate.LessonPlan(sql.FieldGTE(FieldStartDay, v))
}

// StartDayLT applies the LT predicate on the "start_day" field.
func StartDayLT(v int) predicate.LessonPlan {
	return predicate.LessonPlan(sql.FieldLT(FieldStartDay, v))
}

// StartDayLTE applies the LTE predicate on the "start_day" field.
func StartDayLTE(v int) predicate.LessonPlan {
	return predicate.LessonPlan(sql.FieldLTE(FieldStartDay, v))
}

// EndMonthEQ applies the EQ predicate on the "end_month" field.
func EndMonthEQ(v int) predicate.LessonPlan {
	return predicate.LessonPlan(sql.FieldEQ(FieldEndMonth, v))
}

// EndMonthNEQ applies the NEQ predicate on the "end_month" field.
func EndMonthNEQ(v int) predicate.LessonPlan {
	return predicate.LessonPlan(sql.FieldNEQ(FieldEndMonth, v))
}

// EndMonthIn applies the In predicate on the "end_month" field.
func EndMonthIn(vs ...int) predicate.LessonPlan {
	return predicate.LessonPlan(sql.FieldIn(FieldEndMonth, vs...))
}

// EndMonthNotIn applies the NotIn predicate on the "end_month" field.
func EndMonthNotIn(vs ...int) predicate.LessonPlan {
	return predicate.LessonPlan(sql.FieldNotIn(FieldEndMonth, vs...))
}

// EndMonthGT applies the GT predicate on the "end_month" field.
func EndMonthGT(v int) predicate.LessonPlan {
	return predicate.LessonPlan(sql.FieldGT(FieldEndMonth, v))
}

// EndMonthGTE applies the GTE predicate on the "end_month" field.
func EndMonthGTE(v int) predicate.LessonPlan {
	return predicate.LessonPlan(sql.FieldGTE(FieldEndMonth, v))
}

// EndMonthLT applies the LT predicate on the "end_month" field.
func EndMonthLT(v int) predicate.LessonPlan {
	return predicate.LessonPlan(sql.FieldLT(FieldEndMonth, v))
}

// EndMonthLTE applies the LTE predicate on the "end_month" field.
func EndMonthLTE(v int) predicate.LessonPlan {
	return predicate.LessonPlan(sql.FieldLTE(FieldEndMonth, v))
}

// EndDayEQ applies the EQ predicate on the "end_day" field.
func EndDayEQ(v int) predicate.LessonPlan {
	return predicate.LessonPlan(sql.FieldEQ(FieldEndDay, v))
}

// EndDayNEQ applies the NEQ predicate on the "end_day" field.
func EndDayNEQ(v int) predicate.LessonPlan {
	return predicate.LessonPlan(sql.FieldNEQ(FieldEndDay, v))
}

// EndDayIn applies the In predicate on the "end_day" field.
func EndDayIn(vs ...int) predicate.LessonPlan {
	return predicate.LessonPlan(sql.FieldIn(FieldEndDay, vs...))
}

// EndDayNotIn applies the NotIn predicate on the "end_day" field.
func EndDayNotIn(vs ...int) predicate.LessonPlan {
	return predicate.LessonPlan(sql.FieldNotIn(FieldEndDay, vs...))
}

// EndDayGT applies the GT predicate on the "end_day" field.
func EndDayGT(v int) predicate.LessonPlan {
	return predicate.LessonPlan(sql.FieldGT(FieldEndDay, v))
}

// EndDayGTE applies the GTE predicate on the "end_day" field.
func EndDayGTE(v int) predicate.LessonPlan {
	return predicate.LessonPlan(sql.FieldGTE(FieldEndDay, v))
}

// EndDayLT applies the LT predicate on the "end_day" field.
func EndDayLT(v int) predicate.LessonPlan {
	return predicate.LessonPlan(sql.FieldLT(FieldEndDay, v))
}

// EndDayLTE applies the LTE predicate on the "end_day" field.
func EndDayLTE(v int) predicate.LessonPlan {
	return predicate.LessonPlan(sql.FieldLTE(FieldEndDay, v))
}

// StartTimeEQ applies the EQ predicate on the "start_time" field.
func StartTimeEQ(v time.Time) predicate.LessonPlan {
	return predicate.LessonPlan(sql.FieldEQ(FieldStartTime, v))
}

// StartTimeNEQ applies the NEQ predicate on the "start_time" field.
func StartTimeNEQ(v time.Time) predicate.LessonPlan {
	return predicate.LessonPlan(sql.FieldNEQ(FieldStartTime, v))
}

// StartTimeIn applies the In predicate on the "start_time" field.
func StartTimeIn(vs ...time.Time) predicate.LessonPlan {
	return predicate.LessonPlan(sql.FieldIn(FieldStartTime, vs...))
}

// StartTimeNotIn applies the NotIn predicate on the "start_time" field.
func StartTimeNotIn(vs ...time.Time) predicate.LessonPlan {
	return predicate.LessonPlan(sql.FieldNotIn(FieldStartTime, vs...))
}

// StartTimeGT applies the GT predicate on the "start_time" field.
func StartTimeGT(v time.Time) predicate.LessonPlan {
	return predicate.LessonPlan(sql.FieldGT(FieldStartTime, v))
}

// StartTimeGTE applies the GTE predicate on the "start_time" field.
func StartTimeGTE(v time.Time) predicate.LessonPlan {
	return predicate.LessonPlan(sql.FieldGTE(FieldStartTime, v))
}

// StartTimeLT applies the LT predicate on the "start_time" field.
func StartTimeLT(v time.Time) predicate.LessonPlan {
	return predicate.LessonPlan(sql.FieldLT(FieldStartTime, v))
}

// StartTimeLTE applies the LTE predicate on the "start_time" field.
func StartTimeLTE(v time.Time) predicate.LessonPlan {
	return predicate.LessonPlan(sql.FieldLTE(FieldStartTime, v))
}

// EndTimeEQ applies the EQ predicate on the "end_time" field.
func EndTimeEQ(v time.Time) predicate.LessonPlan {
	return predicate.LessonPlan(sql.FieldEQ(FieldEndTime, v))
}

// EndTimeNEQ applies the NEQ predicate on the "end_time" field.
func EndTimeNEQ(v time.Time) predicate.LessonPlan {
	return predicate.LessonPlan(sql.FieldNEQ(FieldEndTime, v))
}

// EndTimeIn applies the In predicate on the "end_time" field.
func EndTimeIn(vs ...time.Time) predicate.LessonPlan {
	return predicate.LessonPlan(sql.FieldIn(FieldEndTime, vs...))
}

// EndTimeNotIn applies the NotIn predicate on the "end_time" field.
func EndTimeNotIn(vs ...time.Time) predicate.LessonPlan {
	return predicate.LessonPlan(sql.FieldNotIn(FieldEndTime, vs...))
}

// EndTimeGT applies the GT predicate on the "end_time" field.
func EndTimeGT(v time.Time) predicate.LessonPlan {
	return predicate.LessonPlan(sql.FieldGT(FieldEndTime, v))
}

// EndTimeGTE applies the GTE predicate on the "end_time" field.
func EndTimeGTE(v time.Time) predicate.LessonPlan {
	return predicate.LessonPlan(sql.FieldGTE(FieldEndTime, v))
}

// EndTimeLT applies the LT predicate on the "end_time" field.
func EndTimeLT(v time.Time) predicate.LessonPlan {
	return predicate.LessonPlan(sql.FieldLT(FieldEndTime, v))
}

// EndTimeLTE applies the LTE predicate on the "end_time" field.
func EndTimeLTE(v time.Time) predicate.LessonPlan {
	return predicate.LessonPlan(sql.FieldLTE(FieldEndTime, v))
}

// HasCompany applies the HasEdge predicate on the "company" edge.
func HasCompany() predicate.LessonPlan {
	return predicate.LessonPlan(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, CompanyTable, CompanyColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasCompanyWith applies the HasEdge predicate on the "company" edge with a given conditions (other predicates).
func HasCompanyWith(preds ...predicate.Company) predicate.LessonPlan {
	return predicate.LessonPlan(func(s *sql.Selector) {
		step := newCompanyStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasSchedules applies the HasEdge predicate on the "schedules" edge.
func HasSchedules() predicate.LessonPlan {
	return predicate.LessonPlan(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, SchedulesTable, SchedulesColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasSchedulesWith applies the HasEdge predicate on the "schedules" edge with a given conditions (other predicates).
func HasSchedulesWith(preds ...predicate.LessonSchedule) predicate.LessonPlan {
	return predicate.LessonPlan(func(s *sql.Selector) {
		step := newSchedulesStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasGrades applies the HasEdge predicate on the "grades" edge.
func HasGrades() predicate.LessonPlan {
	return predicate.LessonPlan(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2M, false, GradesTable, GradesPrimaryKey...),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasGradesWith applies the HasEdge predicate on the "grades" edge with a given conditions (other predicates).
func HasGradesWith(preds ...predicate.Grade) predicate.LessonPlan {
	return predicate.LessonPlan(func(s *sql.Selector) {
		step := newGradesStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasSubjects applies the HasEdge predicate on the "subjects" edge.
func HasSubjects() predicate.LessonPlan {
	return predicate.LessonPlan(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2M, false, SubjectsTable, SubjectsPrimaryKey...),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasSubjectsWith applies the HasEdge predicate on the "subjects" edge with a given conditions (other predicates).
func HasSubjectsWith(preds ...predicate.Subject) predicate.LessonPlan {
	return predicate.LessonPlan(func(s *sql.Selector) {
		step := newSubjectsStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasEducationCategories applies the HasEdge predicate on the "education_categories" edge.
func HasEducationCategories() predicate.LessonPlan {
	return predicate.LessonPlan(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2M, false, EducationCategoriesTable, EducationCategoriesPrimaryKey...),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasEducationCategoriesWith applies the HasEdge predicate on the "education_categories" edge with a given conditions (other predicates).
func HasEducationCategoriesWith(preds ...predicate.EducationCategory) predicate.LessonPlan {
	return predicate.LessonPlan(func(s *sql.Selector) {
		step := newEducationCategoriesStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasUploadFiles applies the HasEdge predicate on the "upload_files" edge.
func HasUploadFiles() predicate.LessonPlan {
	return predicate.LessonPlan(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, UploadFilesTable, UploadFilesColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasUploadFilesWith applies the HasEdge predicate on the "upload_files" edge with a given conditions (other predicates).
func HasUploadFilesWith(preds ...predicate.UploadFile) predicate.LessonPlan {
	return predicate.LessonPlan(func(s *sql.Selector) {
		step := newUploadFilesStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.LessonPlan) predicate.LessonPlan {
	return predicate.LessonPlan(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.LessonPlan) predicate.LessonPlan {
	return predicate.LessonPlan(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.LessonPlan) predicate.LessonPlan {
	return predicate.LessonPlan(sql.NotPredicates(p))
}
