// Code generated by ent, DO NOT EDIT.

package lessonconfirmation

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the lessonconfirmation type in the database.
	Label = "lesson_confirmation"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// FieldLessonReservationID holds the string denoting the lesson_reservation_id field in the database.
	FieldLessonReservationID = "lesson_reservation_id"
	// FieldMatchingDate holds the string denoting the matching_date field in the database.
	FieldMatchingDate = "matching_date"
	// FieldStartTime holds the string denoting the start_time field in the database.
	FieldStartTime = "start_time"
	// FieldFinishTime holds the string denoting the finish_time field in the database.
	FieldFinishTime = "finish_time"
	// FieldRemarks holds the string denoting the remarks field in the database.
	FieldRemarks = "remarks"
	// EdgeLessonReservation holds the string denoting the lesson_reservation edge name in mutations.
	EdgeLessonReservation = "lesson_reservation"
	// Table holds the table name of the lessonconfirmation in the database.
	Table = "lesson_confirmations"
	// LessonReservationTable is the table that holds the lesson_reservation relation/edge.
	LessonReservationTable = "lesson_confirmations"
	// LessonReservationInverseTable is the table name for the LessonReservation entity.
	// It exists in this package in order to avoid circular dependency with the "lessonreservation" package.
	LessonReservationInverseTable = "lesson_reservations"
	// LessonReservationColumn is the table column denoting the lesson_reservation relation/edge.
	LessonReservationColumn = "lesson_reservation_id"
)

// Columns holds all SQL columns for lessonconfirmation fields.
var Columns = []string{
	FieldID,
	FieldCreatedAt,
	FieldUpdatedAt,
	FieldLessonReservationID,
	FieldMatchingDate,
	FieldStartTime,
	FieldFinishTime,
	FieldRemarks,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
	// LessonReservationIDValidator is a validator for the "lesson_reservation_id" field. It is called by the builders before save.
	LessonReservationIDValidator func(int64) error
	// IDValidator is a validator for the "id" field. It is called by the builders before save.
	IDValidator func(int64) error
)

// OrderOption defines the ordering options for the LessonConfirmation queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// ByLessonReservationID orders the results by the lesson_reservation_id field.
func ByLessonReservationID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLessonReservationID, opts...).ToFunc()
}

// ByMatchingDate orders the results by the matching_date field.
func ByMatchingDate(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldMatchingDate, opts...).ToFunc()
}

// ByStartTime orders the results by the start_time field.
func ByStartTime(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStartTime, opts...).ToFunc()
}

// ByFinishTime orders the results by the finish_time field.
func ByFinishTime(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldFinishTime, opts...).ToFunc()
}

// ByRemarks orders the results by the remarks field.
func ByRemarks(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRemarks, opts...).ToFunc()
}

// ByLessonReservationField orders the results by lesson_reservation field.
func ByLessonReservationField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newLessonReservationStep(), sql.OrderByField(field, opts...))
	}
}
func newLessonReservationStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(LessonReservationInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, LessonReservationTable, LessonReservationColumn),
	)
}
