// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/takuyakawta/spot-teacher-sample/db/ent/educationcategory"
	"github.com/takuyakawta/spot-teacher-sample/db/ent/predicate"
)

// EducationCategoryDelete is the builder for deleting a EducationCategory entity.
type EducationCategoryDelete struct {
	config
	hooks    []Hook
	mutation *EducationCategoryMutation
}

// Where appends a list predicates to the EducationCategoryDelete builder.
func (ecd *EducationCategoryDelete) Where(ps ...predicate.EducationCategory) *EducationCategoryDelete {
	ecd.mutation.Where(ps...)
	return ecd
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (ecd *EducationCategoryDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, ecd.sqlExec, ecd.mutation, ecd.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (ecd *EducationCategoryDelete) ExecX(ctx context.Context) int {
	n, err := ecd.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (ecd *EducationCategoryDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(educationcategory.Table, sqlgraph.NewFieldSpec(educationcategory.FieldID, field.TypeInt64))
	if ps := ecd.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, ecd.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	ecd.mutation.done = true
	return affected, err
}

// EducationCategoryDeleteOne is the builder for deleting a single EducationCategory entity.
type EducationCategoryDeleteOne struct {
	ecd *EducationCategoryDelete
}

// Where appends a list predicates to the EducationCategoryDelete builder.
func (ecdo *EducationCategoryDeleteOne) Where(ps ...predicate.EducationCategory) *EducationCategoryDeleteOne {
	ecdo.ecd.mutation.Where(ps...)
	return ecdo
}

// Exec executes the deletion query.
func (ecdo *EducationCategoryDeleteOne) Exec(ctx context.Context) error {
	n, err := ecdo.ecd.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{educationcategory.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (ecdo *EducationCategoryDeleteOne) ExecX(ctx context.Context) {
	if err := ecdo.Exec(ctx); err != nil {
		panic(err)
	}
}
