// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/takuyakawta/spot-teacher-sample/db/ent/lessonconfirmation"
	"github.com/takuyakawta/spot-teacher-sample/db/ent/predicate"
)

// LessonConfirmationDelete is the builder for deleting a LessonConfirmation entity.
type LessonConfirmationDelete struct {
	config
	hooks    []Hook
	mutation *LessonConfirmationMutation
}

// Where appends a list predicates to the LessonConfirmationDelete builder.
func (lcd *LessonConfirmationDelete) Where(ps ...predicate.LessonConfirmation) *LessonConfirmationDelete {
	lcd.mutation.Where(ps...)
	return lcd
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (lcd *LessonConfirmationDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, lcd.sqlExec, lcd.mutation, lcd.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (lcd *LessonConfirmationDelete) ExecX(ctx context.Context) int {
	n, err := lcd.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (lcd *LessonConfirmationDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(lessonconfirmation.Table, sqlgraph.NewFieldSpec(lessonconfirmation.FieldID, field.TypeInt))
	if ps := lcd.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, lcd.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	lcd.mutation.done = true
	return affected, err
}

// LessonConfirmationDeleteOne is the builder for deleting a single LessonConfirmation entity.
type LessonConfirmationDeleteOne struct {
	lcd *LessonConfirmationDelete
}

// Where appends a list predicates to the LessonConfirmationDelete builder.
func (lcdo *LessonConfirmationDeleteOne) Where(ps ...predicate.LessonConfirmation) *LessonConfirmationDeleteOne {
	lcdo.lcd.mutation.Where(ps...)
	return lcdo
}

// Exec executes the deletion query.
func (lcdo *LessonConfirmationDeleteOne) Exec(ctx context.Context) error {
	n, err := lcdo.lcd.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{lessonconfirmation.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (lcdo *LessonConfirmationDeleteOne) ExecX(ctx context.Context) {
	if err := lcdo.Exec(ctx); err != nil {
		panic(err)
	}
}
